CREATE TABLE CITY
(
ID INT,
CITY_NAME VARCHAR(50),
LATITUDE DECIMAL(6,5),
LONGITUDE DECIMAL(6,5),
COUNTRY_ID INT
);

CREATE TABLE CUSTOMER
(
ID INT,
CUSTOMER_NAME VARCHAR(50),
CITY_ID INT,
CUSTOMER_ADDRESS VARCHAR(150),
NEXT_CALL_DATE DATE,
TS_INSERTED DATETIME
);

CREATE TABLE CITY
(
ID INT,
COUNTRY_NAME VARCHAR(50),
COUNTRY_NAME_ENG VARCHAR(50),
COUNTRY_CODE VARCHAR(5)
);